"""empty message

Revision ID: e09c34e4c892
Revises: c9df432a747a
Create Date: 2019-05-19 12:06:58.899264

"""

# revision identifiers, used by Alembic.
revision = 'e09c34e4c892'
down_revision = 'c9df432a747a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_list_entry',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=120), nullable=False),
    sa.Column('affiliation_reference', sa.Unicode(length=30), nullable=True),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], [u'affiliation.object_id'], ),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('email')
    )
    op.add_column(u'user', sa.Column('affiliation_list_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'affiliation_list_entry', ['affiliation_list_entry_id'], ['object_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'affiliation_list_entry_id')
    op.drop_table('affiliation_list_entry')
    ### end Alembic commands ###
