"""empty message

Revision ID: ea5cf08c85a5
Revises: f700386dabdc
Create Date: 2019-07-01 18:57:33.192775

"""

# revision identifiers, used by Alembic.
revision = 'ea5cf08c85a5'
down_revision = 'f700386dabdc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('affiliation_match', sa.Unicode(length=20), nullable=True))
    op.add_column('user', sa.Column('alumni_number', sa.Unicode(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alumni_number')
    op.drop_column('user', 'affiliation_match')
    ### end Alembic commands ###
