"""empty message

Revision ID: f700386dabdc
Revises: e09c34e4c892
Create Date: 2019-06-02 12:41:20.462118

"""

# revision identifiers, used by Alembic.
revision = 'f700386dabdc'
down_revision = 'e09c34e4c892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_addon',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Unicode(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], [u'ticket.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_addon')
    ### end Alembic commands ###
